# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code.
      - uses: actions/checkout@v1
      - name: Set env
        run: echo "RELEASE_VERSION=1.0" >> $GITHUB_ENV

      - run: |
          chmod +x generatePiImage.sh
          ./generatePiImage.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Build-artifact
          path: '**/*.zip'
